import type { Metadata } from "next";
// Correct way to import from the 'geist' package:
import { GeistSans } from 'geist/font/sans'; // Import the font object directly
import { GeistMono } from 'geist/font/mono'; // Import the font object directly

import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import BackgroundParticles from "@/components/BackgroundParticles";

// Fix: Directly assign the imported font objects.
// No need to call them as functions with options.
const geistSans = GeistSans; // Directly assign GeistSans
const geistMono = GeistMono; // Directly assign GeistMono


export const metadata: Metadata = {
  title: "My Portfolio",
  description: "A modern and professional portfolio website.",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      {/* Apply the font variables to the body className */}
      {/* The variable is automatically generated by the Geist import */}
      <body className={`${geistSans.variable} ${geistMono.variable} relative bg-gradient-to-b from-[#1a1a1a] to-[#2c2c2c] text-white min-h-screen`}>
        {/* Background Particles */}
        <BackgroundParticles />

        {/* Content Wrapper */}
        <div className="relative z-10 flex flex-col min-h-screen">
          <Navbar />
          <main className="flex-grow">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}